### ISSUE TITLE
Insert order for processing patterns

### ISSUE THREAD

**Issue by ghost** [refinedmods/refinedstorage#1937]
#### Issue description:
Some machines with multiple slots, e.g. the Slice'n'splice from EnderIO, required that the items are inserted in the correct order. Currently there seems to be no way to force the insertion order, so the crafting does not work.

#### What happens:
The pattern for a Skeletal Contractor requires the silicon to be in the middle slot in the bottom, but the silicon is inserted first in to the bottom left slot. The rotten flesh and skeleton head are not accepted.

#### What you expected to happen:
A way to force the insertion order so that rotten flesh is inserted first.

#### Steps to reproduce:
1. Have a slice'n'splice with a crafter
2. Create a pattern for a skeletal contractor, how the items are placed in the crafting grid does not matter.
3. Request a craft of the skeletal contractor.
4. Look in the slice'n'splice, the items are not in the correct slots.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6

Does this issue occur on a server? [yes/no]
A local LAN server, yes.

**Comment by eihns** [comment]
Maybe just add the items in the order you put it in the crafting field...

Like:

1 2 3 
4 5 6 
7 8 9

So could just insert the first item in the upper left slot, then the second... i guess u get it. Would be an easy fix, i guess?

**Comment by DarkHelmet433** [comment]
I've had this problem with this machine in the past.  I used to solve it by changing the order of the pattern so that the head always came first.  Once the head was inserted, the remaining slots would only accept the correct item.

However in 1.6+ and the new EnderIO, I've literally used the recipe exactly as it's specfied in JEI.
I took a screenshot from my world showing this: https://i.imgur.com/X919G4S.png
In the past I've had to have the head in the top left slot of the pattern.

This machine is quirky at best.

**Comment by eihns** [comment]
The problems continue... alloy smelter... dark steel...

u need crushed coal, iron and obsidian... it first inserts crushed coal and iron... which gives steel...

**Comment by changhe3** [comment]
This would also be very useful for autocrafting using things like AA Empowerer.

**Comment by MarkusPriska** [comment]
Would also really like this feature as i kinda need it for automatic crafting

**Comment by starryknight64** [comment]
I was able to workaround this issue by hooking the crafter up to a chest and have the Slice'n'Splice accept input from the chest.

**Comment by Norway174** [comment]
Having the same problem. Seems like the Crafter will always output the Silicon first, no matter the ordering. Not sure why it selects the silicon first.

@starryknight64's workout doesn't work either, because the machine pulls in the first item from the chest, which is the silicone.

I think @eihns suggestion to use the ordering would be a good, intuitive fix. Which could also potentially solve many more problems, including this one.

**Comment by Salamance73** [comment]
I've come to solve this by using Refined Storage Silicon instead of Raw Silicon from Galacticraft, as the crafter outputs the items into my buffer chest in alphabetical order, meaning Raw Silicon would go before Rotten Flesh. At the moment this seems to work.

**Comment by StewartNZ** [comment]
This has also become an issue in al132mc's mod Alchemistry with the combiner. The inputs need to be a specific order for the machine to create the correct item.

https://github.com/al132mc/alchemistry/issues/57

**Comment by Szasdragon** [comment]
> This has also become an issue in al132mc's mod Alchemistry with the combiner. The inputs need to be a specific order for the machine to create the correct item.
> 
> [al132mc/alchemistry#57](https://github.com/al132mc/alchemistry/issues/57)

Tested some fake recipe patterns and found the Patern recipe not keeps the slot order when there are multiple stacks from same items (there is no difference between stackable and non-stackable). Instead the same items will be stacked together and break the recipe. The Slot Filler item is intended to elevate this issue, but the Crafter not place it correctly.
In the Tool tip window it is useful to see a shortened ingredient list, but for a machine which is sensitive for slot order it isn't.
![image](https://i.imgur.com/zYyLYBX.png)

**Comment by Scha7ten** [comment]
> > This has also become an issue in al132mc's mod Alchemistry with the combiner. The inputs need to be a specific order for the machine to create the correct item.
> > [al132mc/alchemistry#57](https://github.com/al132mc/alchemistry/issues/57)
> 
> Tested some fake recipe patterns and found the Patern recipe not keeps the slot order when there are multiple stacks from same items (there is no difference between stackable and non-stackable). Instead the same items will be stacked together and break the recipe. The Slot Filler item is intended to elevate this issue, but the Crafter not place it correctly.
> In the Tool tip window it is useful to see a shortened ingredient list, but for a machine which is sensitive for slot order it isn't.
> ![image](https://camo.githubusercontent.com/c3e12d133b3b6c4ec5f025067f5ec69a022744d16f885b5e83efa707e2aa9ff8/68747470733a2f2f692e696d6775722e636f6d2f7a59794c5942582e706e67)

You can go around that problem if you set up the crafter with the combiner in a 1:1 ratio per recipe. Meaning: You lock 1 recipe in the combiner and set a crafter up for it with only a single pattern in it. am doing that right now in my playthrough of the chemical exchange modpack (i added some mods to it like flux networks, but nothing that changes rs' behavior). Alchemistry is a pain in the a to automate, but it is possible (and costly, cause if you want your system to run efficiently you need 8 speed upgrades per combiner, 4 in the crafter and 4 in an importer, as the crafter does not seem to pull the items out of the combiner, maybe because the combiner has a strange output slot, which can be filled up by the player with the result).

**Comment by Szasdragon** [comment]
@Scha7ten
Yeah... One combiner for everything in Antimater Chemistry modpack. I had to build minimum 30 or more combiner just for some recipe. I have the space for such system like this, but maintaining it is a nightmare. There is a solution for it. I prefer RS over AE, and it can be improve the mod.
For universal ingot forming, my work around is the Crafter output in a Hopper (side way or else it takes Paterns also), ant this is input to a Combiner. The Combiner is unlocked, so it always make any ingot. But Triglicerin like compounds I have to manually insert them.

**Comment by ImNotIfDumb** [comment]
Is this something that will be fixed in 1.12?

**Comment by Darkere** [comment]
No

**Comment by jonevance** [comment]
If you're like me and still want to play 1.12 for a while, I managed a bit of a workaround.  Doesn't work for everything, but seems to be decent for some stuff.  Place a chest with two servos pulling from it.  A fast one pulls slot fillers always active and a slow one pulls everything else on inverted redstone signal.  Attach the auto-crafter to a hopper feeding that chest with a comparator signaling the slow servo.  Should always then put the slot fillers into the combiner (or whatever) first, then everything else.  As I said, only works for some things, but better than nothing.

![2021-07-28_16 30 49](https://user-images.githubusercontent.com/14884366/127409593-b0179c88-a77e-44b3-b881-ea796852a244.png)

**Comment by RobinVanTol** [comment]
Is this currently fixed for 1.16.5?

**Comment by Darkere** [comment]
Yes. Also for 1.18
