### ISSUE TITLE
Crash and Observations

### ISSUE THREAD

**Issue by Moobien** [refinedmods/refinedstorage#2699]
Hey Raoul, couple of things for you. 

1) my controller started flashing low power and when I right clicked on it I got a CTD. Crashlog for it in this.
2) Disk manipulator exhibiting some really strange placement behaviour.

Stood facing north, placed a controller in front of me. placed a disk manipulator on either side both manipulartors 'appear' to rotate to the north, however when a disk is inserted pyou can see it where it is supposed to be.  Place controller facing south, both manipulators appear to place correctly. Place controller facing east, both manipulators 'appear' to place facing the south with the inserted disk beeing where it should be.  same thing happens when placed facing west. if you place a manipulator down and it is NOT connected to the rs network it places fine but the second it gets connected to the network the above glitches happen. 

3) when a grid is set to 'display only craftables' it only displays the patterns, it doesn't display the quantity of the craftable item. 

- Minecraft: 1.16.3
- Forge: 34.1.1
- Refined Storage: 1.9.6

https://pastebin.com/knMn0zVP

https://imgur.com/a/8HvuZ4o

**Comment by Darkere** [comment]
1. Crash is fixed in 1.9.7
2. I am utterly confused how this happens. The models are correct, the blockstate direction property stays the same.... I can confirm that the diskmanipulator model rotates 180 degrees between when connected/disconnected

3. This is true. And could be considered a bug as in previous versions it did show the amount available.
