### ISSUE TITLE
[Maven Repo] Upload legacy builds to maven repository

### ISSUE THREAD

**Issue by Dragovorn** [refinedmods/refinedstorage#2724]
It seems that when you refactored the maven repo older builds were lost, the only available builds are for 1.15, and all 1.12 builds are missing from the maven repo, could you please upload the older builds to the repo so that mods for those older versions can properly fetch their required dependencies.

**Comment by raoulvdberge** [comment]
The removal of old builds from the Maven repo is unrelated to the refactoring I did recently.

I explictly removed those old versions from Jenkins and Maven because we were close to running out of disk space. Also, 1.12 is no longer supported so that made removing those builds a little easier.

It's unfortunate, but I have to work with the constraints I have with regards to the build server.
If you wish to continue using 1.12 builds, I recommend building an API jar yourself and referencing that.

**Comment by Dragovorn** [comment]
I see, understandable, thank you for the quick response!
