### ISSUE TITLE
Feature Request: External Storage (or Exporter) "Always Export" option

### ISSUE THREAD

**Issue by ariosos** [refinedmods/refinedstorage#2800]
For the lack of a better term, I would like for the External Storage (or exporter) to constantly push items, in this case, to a Storage Drawer Controller. Unless there's a clever way to do what I'm describing, I have a storage drawer system for bulk storage. If that storage gets filled, it backs up into the Refined Storage drives, and I have to have an exporter for each drawer I want to send the items back to (i.e., after I upgrade a drawer to the next tier, or add a void upgrade). It would be simpler if I could say "export anything" to the drawer controller and rely on the locked drawers being the filters.

I vaguely recall doing something similar to this with AE2 back in 1.7.10, but even that had issues with drawer controllers sometimes. What I did once was to have only a large overflow chest, plus drawers, and an exporter from the chest going back into the storage drawers. That's what I'm trying to achieve with the drives themselves. Treat drives as the overflow, and if there's room in primary storage, put it there.

**Comment by uecasm** [comment]
I assume you have an External Storage on the drawer controller?  That's the Right Way™ to do it, not using an exporter.

Adding void upgrades to the storage drawers is the simplest option to deal with overflow.  That way, anything you've explicitly said "I don't care if I lose this" will just get voided and not clog your storage, and anything else **will** back up and clog your storage, until you notice and decide how to deal with it -- either by adding a void upgrade or a storage upgrade, depending on whether you want to lose the item or not.  (Or turning off whatever is producing the items.)

Another option is to have your drawer storage set to a higher priority, then have a medium priority storage (not an exporter!) on a trashcan, with the main storage a lower-still priority.  You'll need to be **very** sure that you have the storage in whitelist mode with the appropriate items set in the filter before you actually connect it to your network, otherwise you'll have a bad time.

The other way is to use the Detector to detect when your drawers are getting close to full, and then turn off whatever is producing the item.  This requires you to have a single machine dedicated to producing that item, and which can stop running or fill up without breaking any other processing lines.

Or a fourth alternative was part of the motivation why I just wrote my own addon mod: you make it [only craft what it actually needs to in the first place](https://github.com/uecasm/rs4cc/wiki/Storage-Monitor).

**Comment by ariosos** [comment]
Yes, that's what I normally do. I just wanted to make sure everything was in storage drawers before putting the storage bus on it. Maybe I'll just export to a bunch of interfaces, and use an item pipe to transfer items into the storage drawer network, then storage bus the interfaces to check for overflow there.
