### ISSUE TITLE
World Breaking! RS Hard Crash Server Exception in Server Loop, Network Direction.

### ISSUE THREAD

**Issue by desagas** [refinedmods/refinedstorage#2946]
#### Issue description:
Turning off a network transmitter (redstone controlled) crashed server.

#### What happens:
I clicked on the level beside my network transmitter, and the game crashed.

When world loads back up, everything is fine, level is switched, and the network is working as intended. But, every time I flip the lever, on or off, the game crashes. Actually, after it crashing a second time, it is now a world breaking crash, meaning that I can not laod my world without it crashing immediately.

#### Steps to reproduce:
1. Place transmitter, place receiver, shift right click receiver, place in receiver (network card).
2. Set receiver to be redstone active.
3. Flip lever.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.2
- Refined Storage: refinedstorage-1.9.12.jar

Does this issue occur on a server? [yes/no] NO

#### If a (crash)log is relevant for this issue, link it here: https://gist.github.com/desagas/d632f9699bb7823cf29d06bd9683986c

Latest.log, cut to this crash: https://gist.github.com/desagas/5fb02f0cb049015cc77a22daadd35df0

[pastebin/gist/etc link here]

**Comment by jeremiahwinsley** [comment]
We are experiencing the same issue on a server running the ATM6 Sky modpack - Forge 36.1.24, RS 1.9.12

Latest crashlog: https://gist.github.com/jeremiahwinsley/f839c29f63faaee00f5f96f00d1a4978

**Comment by iTrooz** [comment]
Hey, here is some more info on the issue I've found while doing an hotfix

First, here is the hotfix : https://gist.github.com/iTrooz/5d1b12e45a47760e3deae8d8fc079759
From what I understand, the problem is that when the world start, RS is ticking blocks of every network and do stuff with them, and for some reason, he happens to call getDirection() on a cable (don't know why bc I wasn't able to reproduce the issue, but this has something to do with network importers or external storage, as they appear in the stacks)
The hotfix is simply checking wheter the BlockState has a "getDirection" property, if not, it returns a default value (DOWN rnin my case
This fix is currently running on the ATM6 server that had the issue yesterday

@desagas could you try to reproduce it in solo, and give us more precise steps ? I was not able to reproduce the issue ):

If anyone wants, here is a patched jar : https://cdn.discordapp.com/attachments/851475000421777428/851476586216554536/refinedstorage-1.9.13.jar

**Comment by TheJulianJES** [comment]
I also tried to reproduce this issue in the latest RS version (1.9.15) and was unable to. I don't think it has been patched though.
If possible, please give clear steps (a video or screenshots would also be nice) (or even a minimal world download?).

**Comment by desagas** [comment]
Oh geez. I’m done with that world and it’s long gone. I’m about to start a new RS network in a different pack, and the same pack now update sometime in the near future. When I get there, I’ll test it again, and then post my results here.

Almost 4 months for me is like 5 worlds. Hahah. I wish I wasn’t so adhd and could actually commit to a full building world.
