### ISSUE TITLE
Server on a crash loop

### ISSUE THREAD

**Issue by captain-hedgehog** [refinedmods/refinedstorage#3007]
#### Issue description:
Single server tick took 60.00 seconds (should be max 0.05)

#### What happens:
Server is stuck on a crash loop
Clean wipe followed by loading a backup from 2 days ago still gives the same crash loop even though the server was running fine back then

#### What you expected to happen:
Server to start normally

#### Steps to reproduce:
Unable to reproduce in single player

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.23
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/EcLkB7z2

**Comment by Darkere** [comment]
Try increasing max-tick-time in server.properties.

If that doesn't help, open world/data/refinedstorage_networks.dat with nbt explorer and find the crafting task and delete it. 

Otherwise from what I'm looking at, next release should fix the performance problem that causes the lag there (most likely caused by a crafter from another mod).
