### ISSUE TITLE
Can no longer click to see recipes in JEI if GUI has ghost item handler

### ISSUE THREAD

**Issue by Chunkimunki** [refinedmods/refinedstorage#3031]
Unable to use latest  JEI versions to auto complete recipes for patterns - only works if item is 'favourited'.

Crafting grid just flashes green when item clicked in JEI - no recipes shown.
 
 
SinglePlayer

- Minecraft: 1.16.5
- Forge: 36.1.32
- Refined Storage: 1.9.13
- JEI : 36.1.32  ( went back 15 versions - issue still present )

**Comment by DarkHelmet433** [comment]
I am hitting this too, unfortunately.

**Comment by necauqua** [comment]
This is a new JEI feature - can now drag ghost items from jei into slots, so LMB starts dragging instead of opening the recipe.

You have to use a keybind to open the recipe, or maybe make a jei issue so that LMB press and release opens a recipe and LMB press and drag does the new thing.

Not caused by RS

**Comment by Darkere** [comment]
JEI version 87 works

**Comment by DarkHelmet433** [comment]
It seems you can sort-of work around it without a keybind.  Right click the item for finding its uses, then immediately left-click.  The JEI "uses" tab will be replaced with the crafting recipe with the usual [+] for copying.  This is awkward though.

**Comment by DarkHelmet433** [comment]
Upstream bug: mezz/JustEnoughItems#2352

**Comment by Darkere** [comment]
Using the keyboard shortcut for recipe lookup works fine too :)

**Comment by Darkere** [comment]
Has been fixed by JEI
