### ISSUE TITLE
Utterly massive server lag 

### ISSUE THREAD

**Issue by egshels** [refinedmods/refinedstorage#3072]
#### Issue description:
When a player joins my server, TPS drops to 3 for around 20 minutes. It usually crashes before this is done. I only know it's due to Refined Storage because my Spark profiler report has almost all of the load attributed to Refined Storage.

#### Steps to reproduce:
1. Unsure. Have several large Refined Storage systems loaded?
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.2
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no]
Yes
Here's the Spark profiler report:
https://spark.lucko.me/Dl17QqsAki

**Comment by Darkere** [comment]
Something appears to be rebuilding the network very often. Check on RS networks for power loss or maybe redstone clocks enabling/disabling parts of the network with a relay.

**Comment by bloodscon** [comment]
seen this on a server I used to join when someone set up detectors attached to a system that maintained a level of charcoal but they had it setup wrong. what they had was detectors into relay set at less then 512 charcoal then after the relay was a bank of 12 redstone furnaces with importers on and exporters (no speed or stack upgrades) so when the system was below 512 charcoal these 12 importer and 12 exports activated now that looks ok but the main base used charcoal for power so is would drop below 512 activate put wood in furnaces and pull out charcoal but with no stack upgrades only one charcoal out of each furnace was pulled till the limit of 512 was reached his system used about 4 charcoal a sec and as such the system was forever switching on and off.  Server admin ended up breaking the relay and kindly showed him and anyone that wanted to know how to setup a bulk system using only RS by having another RS network deal with his charcoal (yes there was other pipe mods but they wanted to show how to do it with just RS)

main RS detector set to less then 512 charcoal > exported set to wood (with stack upgrade) > chest (chest had all but one slot filled with cobble (you could use any single slot chest) new RS network set up with storage interface on the chest whitelisted to wood then exporters and importers on furnace connected to the new RS network another chest setup one space away from the import chest and the new RS network connected to it with storage interface the old system was attached to this chest with a imported so now instead of 24 interfaces switching on and off it's down to 1 even better later on he ended up using it to process iron > steel

**Comment by egshels** [comment]
> Something appears to be rebuilding the network very often. Check on RS networks for power loss or maybe redstone clocks enabling/disabling parts of the network with a relay.

That was it! Someone on my server didn't have enough power to run their system all the time, so it was turning off and on again. Thank you very much!
