### ISSUE TITLE
Disk Drives and Disks do not work

### ISSUE THREAD

**Issue by 100chilly** [refinedmods/refinedstorage#3250]
### Describe the bug

Trying to use disk drives and disks and they do not work. You can get an ID assigned to them but trying to fill them with items doesn't work using a crafting grid or normal grid. Storage Blocks do work weirdly enough however. If I had to guess, it may be something to do with #3202 but there's no erroring in the logs.

The mod list is as follows
[1.18.1] SecurityCraft v1.9.0.2-beta1.jar
additional-guns-0.4.2-1.18.1.jar
AdLods-1.18.1-5.0.0.1-build.0061.jar
AI-Improvements-1.18-0.4.0.jar
alloyed-1.18.1-v1.2.jar
alwaysawitherskull_1.18.1-1.5.jar
AmbientSounds_v5.0.9_mc1.18.1.jar
angelring-1.18-1.5.0.jar
anvilrestoration_1.18.1-1.2.jar
Aquaculture-1.18.1-2.3.3.jar
architectury-3.7.22.jar
areas_1.18.1-2.9.jar
Assembly Line-1.18.1-0.4.0-0.jar
AttributeFix-Forge-1.18.1-13.0.5.jar
AutoRegLib-1.7-53.jar
Ballistix-1.18.1-0.5.0-0.jar
balm-2.4.3+0.jar
BeeFix-1.18-1.0.0.4.jar
BetterF3-1.2.2-Forge-1.18.jar
BetterTitleScreen-1.18-1.12.0.jar
BiomesOPlenty-1.18.1-15.0.0.105-universal.jar
blacksmiths-1.1.0-forge.jar
Blastcraft-1.18.1-0.2.5-0.jar
BorderlessWindow-1.18-1.4.0.jar
buildinggadgets-3.12.0-build.4+mc1.18.1.jar
caelus-forge-1.18.1-3.0.0.2.jar
camera-1.18.1-1.0.2.jar
campfirespawnandtweaks_1.18.1-1.5.jar
carryon-1.18.1-1.17.0.7.jar
catalogue-1.6.0-1.18.1.jar
Chargers-1.18.1-4.1.0.12.jar
cloth-config-6.2.57-forge.jar
collective-1.18.1-4.7.jar
ColossalChests-1.18.1-1.8.2.jar
comforts-forge-1.18.1-5.0.0.2.jar
compacthelpcommand_1.18.1-1.2.jar
compactmachines-4.0.0-beta.4.jar
configured-1.5.3-1.18.1.jar
connectivity-1.18-2.6.jar
constructionwand-1.18.1-2.6.jar
controllable-0.15.1-1.18.jar
cookingforblockheads-forge-1.18.1-11.1.0.jar
CosmeticArmorReworked-1.18.1-v1a.jar
craftingtweaks-forge-1.18.1-14.0.2.jar
create-mc1.18.1_v0.4d.jar
createaddition-1.18.1-20220125a.jar
createdeco-1.2.5-1.18.jar
createfa-1.18.1_v1.0.8.jar
CreativeCore_v2.5.0_mc1.18.1.jar
Croptopia-1.18-FORGE-1.8.1.jar
Cucumber-1.18.1-5.0.3.jar
curioofundying-forge-1.18-5.3.0.0.jar
curios-forge-1.18.1-5.0.6.1.jar
curiouselytra-forge-1.18.1-5.0.1.0.jar
curiousshulkerboxes-forge-1.18.1-4.2.0.0.jar
Cyclic-1.18.1-1.6.13.jar
CyclopsCore-1.18.1-1.13.0.jar
doubledoors_1.18.1-3.2.jar
dragondropselytra_1.18.1-1.5.jar
drinkbeer-v2.3.5 for 1.18.1.jar
DungeonCrawl-1.18.1-2.3.7.jar
Dynamic Electricity-1.181-0.3.2-1.jar
dynview-1.18.1-2.4.jar
easyelytratakeoff_1.18.1-2.2.jar
EasyMagic-v3.2.1-1.18.1-Forge.jar
Electrodynamics-1.18.1-0.5.9-0.jar
enchantingcommands_1.18.1-1.8.jar
EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar
enderchests-1.18-1.9.0.jar
endertanks-1.18-1.11.1.jar
engineersdecor-1.18.1-1.1.19.jar
Extended Tools-1.18.1-0.3.4-0.jar
extendedcreativeinventory_1.18.1-1.7.jar
ExtraDisks-1.18.1-2.0.2.jar
ExtraStorage-1.18.1-2.0.1.jar
ExtremeReactors2-1.18.1-2.0.38.jar
farmingforblockheads-forge-1.18.1-9.0.3.jar
farsight-1.18-1.6.jar
FastFurnace-1.18.1-6.0.2.jar
FastLeafDecay-27.2.jar
FastSuite-1.18.1-3.0.0.jar
FastWorkbench-1.18.1-6.0.1.jar
feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.jar
ferritecore-4.1.2-forge.jar
flatbedrock-1.4.1-build.8+mc1.18.1.jar
flywheel-forge-1.18-0.6.0.jar
ForgeEndertech-1.18.1-8.0.1.0-build.0059.jar
framework-0.2.3-1.18.1.jar
ftb-chunks-forge-1801.3.4-build.127.jar
ftb-essentials-1801.1.6-build.37.jar
ftb-library-forge-1801.3.5-build.109.jar
ftb-quests-forge-1801.3.7-build.93.jar
ftb-ranks-forge-1801.1.6-build.22.jar
ftb-teams-forge-1801.2.5-build.48.jar
ftb-ultimine-forge-1801.3.2-build.48.jar
furniture-7.0.0-pre28-1.18.1.jar
Gobber2-Forge-1.18.1-2.6.18.jar
gravestone-1.18.1-1.0.2.jar
gun-mod-1.1.3-1.18.1.jar
handoveryouritems_1.18.1-1.4.jar
healingcampfire_1.18.1-3.4.jar
ImmersiveEngineering-1.18.1-7.1.0-145.jar
Industrial Agriculture[Core]-1.18.1-1.8.17.jar
Industrial Agriculture[Gobber]-1.18.1-1.8.13.jar
infinitetrading_1.18.1-2.0.jar
inventoryessentials-forge-1.18-4.0.0.jar
ironchest-1.18-13.0.7.jar
ironfurnaces-1.18.1-3.1.4.jar
IronJetpacks-1.18.1-5.0.2.jar
item-filters-forge-1801.2.6-build.16.jar
jei-1.18.1-9.4.1.106.jar
jmi-1.18.1-0.8-44.jar
journeymap-1.18.1-5.8.0beta15.jar
just_enough_keg-1.18.1-3.0.0.jar
justenoughkeys-0.5.3-forge.jar
JustEnoughProfessions-1.18-1.2.2.jar
JustEnoughResources-1.18.1-0.13.2.153.jar
krypton-1.0.0.jar
Ksyxis-Forge1.17-1.1.jar
light-overlay-6.0.4-forge.jar
lootr-1.18-0.1.14.48.jar
macawsbridgesbop-1.18.1-1.0.jar
MapFrontiers-1.18.1-1.5.2beta1.jar
mcjtylib-1.18-6.0.9.jar
mcw-bridges-2.0.1-mc1.18.1.jar
mcw-doors-1.0.5-mc1.18.1.jar
mcw-fences-1.0.2-mc1.18.1.jar
mcw-lights-1.0.2-mc1.18.1.jar
mcw-paintings-1.0.2-mc1.18.1.jar
mcw-roofs-2.1.0-mc1.18.1.jar
mcw-trapdoors-1.0.4-mc1.18.1.jar
mcw-windows-2.0.2-mc1.18.1.jar
mineralchance_1.18.1-1.7.jar
mininggadgets-1.10.2.jar
MouseTweaks-forge-mc1.18-2.21.jar
MysticalAgradditions-1.18.1-5.0.3.jar
MysticalAgriculture-1.18.1-5.0.3.jar
NaturesCompass-1.18.1-1.9.4-forge.jar
netherportalfix-forge-1.18-9.0.0.jar
no-telemetry-1.3.0.jar
no_null_processors_forge-2.0.2+1.18.1.jar
nohostilesaroundcampfire_1.18.1-3.9.jar
Nuclear Science-1.18.1-0.4.6-0.jar
Patchouli-1.18.1-65.jar
PickleTweaks-1.18.1-6.0.2.jar
pipez-1.18.1-1.0.1.jar
Placebo-1.18.1-6.1.1.jar
polymorph-forge-1.18.1-0.37.jar
PuzzlesLib-v3.2.1-1.18.1-Forge.jar
Quark-3.1-340.jar
QuarkOddities-1.18.jar
radium-0.7.7g.jar
randomvillagenames_1.18.1-1.5.jar
rangedpumps-0.9.0.jar
refinedstorage-1.10.0.jar
refinedstorageaddons-0.8.1.jar
repurposed_structures_forge-4.2.11+1.18.1.jar
rftoolsbase-1.18-3.0.5.jar
rftoolsbuilder-1.18-4.0.6.jar
rftoolspower-1.18-4.0.3.jar
rftoolsstorage-1.18-3.0.5.jar
rftoolsutility-1.18-4.0.9.jar
RingsOfAscension-1.18-1.0.0.jar
rubidium-0.5.0.jar
saveandloadinventories_1.18.1-1.7.jar
scaffoldingpower-1.18-1.3.0.jar
shetiphiancore-1.18-3.10.3.jar
shulkerdropstwo_1.18.1-1.8.jar
simplemagnets-1.1.5-mc1.18.jar
smallernetherportals_1.18.1-1.9.jar
SoL-Carrot-1.18.1-1.12.0.jar
SolarGeneration-1.18.1-4.0.0.jar
sophisticatedbackpacks-1.18.1-3.15.9.533.jar
starlight-1.0.1+forge.36a1c6c.jar
starterkit_1.18.1-3.2.jar
steampowered-1.18.1-2.0.0-alpha.jar
StorageDrawers-1.18.1-10.1.1.jar
supermartijn642configlib-1.0.9-mc1.18.jar
supermartijn642corelib-1.0.16b-mc1.18.jar
taterzens-1.8.4-forge.jar
TerraBlender-forge-1.18.1-1.1.0.73.jar
theoneprobe-1.18-5.0.3.jar
toofast-1.18-0.0.1.2.jar
ToolBelt-1.18-1.18.0.jar
tradernpcs-1.1.0-forge.jar
trashslot-forge-1.18.1-11.0.2.jar
treeharvester_1.18.1-4.2.jar
veinmining-forge-1.18.1-0.17.jar
villagebellrecipe_1.18.1-1.4.jar
villagernames_1.18.1-3.5.jar
waystones-forge-1.18.1-9.0.4.jar
worldedit-mod-7.2.9.jar
xptome-1.18.1-2.1.4.jar
ZeroCore2-1.18.1-2.1.11.jar

### How can we reproduce this bug or crash?

1. Place down a controller, disk drive, grid, and power and have them all hooked up.
2. Insert disks into drive and make sure drive is powered.
3. Attempt to use the grid and insert items.
4. Nothing happens.

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.0.88

### What Refined Storage version is this happening on?

1.10.0

**Comment by SG1K** [comment]
Hey I'm not sure if anybody has seen this post, but I had the same issue.
I was playing on my fairly new _singleplayer_ world ("Supercraft 3") and when I teleported back from the **"End Dimension"** using
an **Advanced Charged Porter** **(mod: "RFTools")**, I dumped all of the items 
(from mining & killing mobs in the End Dimesnion) into my storage system.
Then things became really weird.
I went to my basement to check my smelting system and a few other machines from different mods **(mods: "EnderIO" , "NuclearCraft")**, but when I came back up, I checked my storage system because I needed to put some stuff that I grabbed from the basement (mostly ingots, but also some stone), and was shocked to see that all of the stuff in my Crafting Grid
**(mod: Refined Storage")** became invisible!
I even changed my _gamemode_ from _survival_ to _creative_ to test some of the stuff, but I wasn't able to figure anything out.
_I even logged out of the world and logged back in, to see if the system would work again, but it didn't._
For like 10 minutes straight I was messing around, breaking and replacing the Disk Drive, Controller and the Crafting Grid multiple times, I changed their place (basically swapped them around) to see if it would maybe fix it, but it didn't.
_Then I even broke the **Chunk Loader** from the **"Chicken Chunks"** mod, and it also didn't help._

This is not a modpack, I'm just a guy who's playing basic modded MC with all the mods downloaded from the "CurseForge" website
and put into minecraft via "Forge".

**If anybody out there knows the answer to this problem, please answer to this comment or just contact me through Discord!**
**My Discord username is: SG1000#1783**

**Minecraft version 1.12.2**

**The list of all the mods in my world:**

[1.12.2]DamageIndicatorsMod-3.5.1.jar
ActuallyAdditions-1.12.2-r152.jar
Advanced+Solar+Panels-4.3.0.jar
AutoRegLib-1.3-32.jar
Avaritia-1.12.2-3.3.0.37-universal.jar
AvaritiaTweaks-1.12.2-1.3.jar
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
Botania+r1.10-364.4.jar
BrandonsCore-1.12.2-2.4.17.208-universal.jar
calculator-1.12.2-5.0.12-15.jar
ChickenChunks-1.12.2-2.4.2.74-universal.jar
Chisel-MC1.12.2-1.0.2.45.jar
Cyclic-1.12.2-1.20.8.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar
CTM-MC1.12.2-1.0.2.31.jar
Cucumber-1.12.2-1.1.2.jar
Decocraft-2.6.3.7_1.12.2.jar
device-mod-0.4.1-1.12.2.jar
Draconic-Evolution-1.12.2-2.3.24.349-universal.jar
ElevatorMod-1.12.2-1.3.14.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.3.70.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
environmentaltech-1.12.2-2.0.20.1.jar
ExtraPlanets-1.12.2-0.7.4.jar
extrautils2-1.12-1.9.9.jar
forestry_1.12.2-5.8.2.422.jar
furniture-6.3.1-1.12.2.jar
GalacticraftCore-1.12.2-4.0.2.280.jar
Galacticraft-Planets-1.12.2-4.0.2.280.jar
Gendustry-Mod-1.12.2.jar
gravestone-1.10.3.jar
GunpowderLib-1.12.2-1.0.jar
HammerLib-1.12.2-2.0.6.23.jar
Hwyla-1.8.26-B41_1.12.2.jar
iceandfire-1.9.1-1.12.2.jar
ImmersiveEngineering-0.12-98.jar
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.10.jar
industrialcraft-2-2.8.178-ex112.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.59.842.jar
jei_1.12.2-4.16.1.301.jar
jeibees-0.9.0.5-mc1.12.2.jar
LibraryEx-1.12.2-1.2.2.jar
llibrary-1.7.19-1.12.2.jar
MagicBees-1.12.2-3.2.25.jar
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
Mantle-1.12-1.3.3.55.jar
mcjtylib-1.12-3.5.4.jar
Mekanism-1.12.2-9.8.3.390.jar
MicdoodleCore-1.12.2-4.0.2.280.jar
MysticalAgradditions-1.12.2-1.3.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
MJRLegendsLib-1.12.2-1.2.1.jar
MobGrindingUtils-0.3.13.jar
natura-1.12.2-4.3.2.69.jar
NetherEx-1.12.2-2.2.5.jar
NotEnoughIDs-1.5.4.4.jar
NotEnoughItems-1.12.2-2.4.3.245-universal.jar
NuclearCraft-2.18y-1.12.2.jar
Pam's+HarvestCraft+1.12.2zg.jar
pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar
PTRLib-1.0.5.jar
Quark-r1.6-179.jar
RebornCore-1.12.2-3.19.5-universal.jar
RedstoneArsenal-1.12.2-2.6.3.18-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
refinedstorage-1.6.16.jar
Reliquary-1.12.2-1.3.4.796.jar
rftools-1.12-7.73.jar
rftoolsdim-1.12-5.71.jar
SilentLib-1.12.2-3.0.14+168.jar
SilentsGems-1.12.2-2.8.22+327.jar
SimplyJetpacks2-1.12.2-2.2.18.1.jar
sonarcore-1.12.2-5.0.19-20.jar
TechReborn-1.12.2-2.27.3.1084-universal.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicAdditions-1.12.2-12.6.7.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
valkyrielib-1.12.2-2.0.20.1.jar
Xaeros_Minimap_21.22.6_Forge_1.12.jar
xnet-1.12-1.8.2.jar

**(105 mods in total)**

**Comment by raoulvdberge** [comment]
Hi, ensure that your disk drive is in the correct filtering mode.
