### ISSUE TITLE
ctrl + click for alternatives is not working

### ISSUE THREAD

**Issue by penturt** [refinedmods/refinedstorage#3354]
### Describe the bug

ctrl + click for alternatives in pattern grid is not working in latest release v1.10.3

### How can we reproduce this bug or crash?

try bring up the alternatives selector during pattern creation 

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

1.18.2 - 40.1.69

### What Refined Storage version is this happening on?

v1.10.3

**Comment by Nevrai** [comment]
It works for me in the same Minecraft, Forge, and Refined Storage version, but that’s only when creating processing patterns. Ctrl-clicking to set alternatives in a regular crafting pattern does not work. I’m not sure whether this is a bug or intentional, but you _can_ use exact mode. However, being able to select a specific tag for alternatives for a regular crafting pattern would be very handy, so I’m not sure whether this is a bug or just a missing feature.

**Comment by marlester-dev** [comment]
Maybe Ctrl + Shift + Left Click?

**Comment by raoulvdberge** [comment]
alternatives only work in processing mode.
