### ISSUE TITLE
Not letting me take stuff out of grid (Techopolis 2)

### ISSUE THREAD

**Issue by TheOGKynes** [refinedmods/refinedstorage#3592]
### Describe the bug

Whenever I try to take anything out of any grid (including wireless) it just wont let me do it, any external transport works, such as exporters and autocrafting still works aswell.

### How can we reproduce this bug or crash?

Have a system
Try to take stuff out
Idk

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.3.2

### What Refined Storage version is this happening on?

1.11.6

**Comment by Wishbone1977** [comment]
This happens when you have external storages connected directly to inventory blocks (a drawer for instance, rather than a controller) the contents of which change constantly and rapidly. I ran into the same problem in Techopolis 2. Try to only use external storage on controllers and see if it doesn't help.

It is a bug of course, but given the nature of the problem it's hard to do anything about it other than working around it.

**Comment by raoulvdberge** [comment]
#2568
