### ISSUE TITLE
Pattern Redstone signal to item/fluid.

### ISSUE THREAD

**Issue by puggan** [refinedmods/refinedstorage#3668]
### Describe your enhancement

Exemple, I have a block that produce water if I give it an redstone sinal.

It would be nice if I could put a crafter next to it, with a pattern that said redstone-signal -> water.
And if I order some blue Ice, that needs a lot of water, the crafter activates the restone signal until I revived enough water.

My current workaround is to have it always running, filter my fluid-storage so it stops when selected storage is full,
and then i have a 1 cobelstone-> 64B water recipts that connected to a chest.
That way I can order more BlueIce than I currently have water for, and it just put some cobelstones in the chests and wait for the water.

**Comment by raoulvdberge** [comment]
We can't treat redstone as an autocrafting input. There are better ways to solve your issue.

**Comment by Nodrance** [comment]
I think what they're referring to is this block from AE2, with a crafting card
https://guide.appliedenergistics.org/1.20.4/items-blocks-machines/level_emitter
The function here is essentially "if this item is being requested for a craft, emit redstone". For example, you could put a nether star in it, and anytime a nether star is requested, it gets a redstone signal that turns on your wither farm.

**Comment by Peekofwar** [comment]
I think the idea is to have a crafter that sends a redstone signal instead of an item to a block, which then activates a system to produce the item that is being requested. 

Technically you could achieve something similar by using the Detector, however this means it will always activate based on how much is in the system rather than actual requirement. There's also the issue that the Detector won't tell the system it can expect to have an amount of items when you need an amount of items greater than currently available to start a large crafting order.

**Comment by Nodrance** [comment]
Indeed. It works great for something like crafting octuple compressed cobblestone, where you can make enough for it by turning on your cobble gen but don't want to do it in parts or have 43 million cobble lying around at once.
