### ISSUE TITLE
Enable inserting items into a Storage Monitor block without the need to have the item to insert as the currently selected item.

### ISSUE THREAD

**Issue by calloatti** [refinedmods/refinedstorage#3686]
### Describe your enhancement

Right now you can extract items from a Storage Monitor block with an empty hand or any arbitrary active item in hand by left clicking. Of course the item to be extracted is defined by the item configured in the Storage Monitor block.

To insert items by right clicking into a Storage Monitor, the item to insert must be the active item in hand, I propose items should also be inserted with an empty hand or any arbitrary active item, since the intended item to insert is indicated by the configured item in the Storage Monitor.

The current situation requires that you select the item twice, once by configuring the Storage Monitor, and a second time by making the item the currently selected item. Seems redundant.

**Comment by raoulvdberge** [comment]
The reason for this requirement is so that we know which slot the player wants to insert. If you hold something other than the configured item, which slot would we take first? Or would we try to insert all slots?

I understand your complaint, and the current way of working might be a little limited, but it's at least clear for everyone what the behavior will be.
